---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBwJEu0HVXI0fKhJ/TIuhLcF1QP4DHEBC1+PjBmvjMLZdAybLZuVMN6gQE4b1uzbjtWz5wCdkHTYIgnL+GmY0ruUplQX6s9x8CXM20No1xzGs+3YJsV6toH+0cRZESelEVleJf/Ym744PStupF28njrIqZa9ucIkzjNap5e/5V/Ma7ne1ADyp8+Di3UTVEpigPd07osbYunUpn8R3nwHoL5HMegT8fWu+A9LtRSFtziv6KQ2rlTX69RB0nkwtaduw3A/VEUDWRRbNGizalVwhOWOqKHdUaUbL2X0x1bd9l2fkEGQAmk4iZT0Pe8EN6SbOYr+ye7wjeA3zB1xj9iDoQ628KhqRf5QAkXkv7/vAkcMHGFVPIK6lzowVcItx7MRlS+RaGbmDs4JiAIQD91agiDf7jjmXKIT883VuiGPV98XJmHwn+FsuA5nSr1zOls8aRafeLg+68Cs7NattJrRYmWl7x5n0gq8I7PNExZQxBG2B/capdZiOgH89/e06rnKDSPMRhqKq99wz7fU3ybO7ngeYQaHWZ1BwY7IfI0X50GzjL1mblSCor9NrYHoDhKBBJxqE+rJ9WgnRbypi9tVYqPmj8nYGDOpt3nnow1krFoV0KODQu6PFq30fj8tG+PicON53Ni6brP0lNv14+OjKuJ1nUotrNCqfNk3SGv1EZW8hWZGtgC3ZGgqU7JOeH0ohRB3pvO/VChXFnppRqjWogL8946
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque
